package com.foretruff.jdbc.starter;

import com.foretruff.jdbc.starter.util.ConnectionManager;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


public class JdbcRunner {
    public static void main(String[] args) throws SQLException {
        getTicketsByFlightId("1 OR 1 = 1").forEach(System.out::println);
    }

    private static List<Long> getTicketsByFlightId(String flightId) throws SQLException {
        String sql = """
                    SELECT id
                    FROM ticket
                    WHERE flight_id = %s
                """.formatted(flightId);
        List<Long> result = new ArrayList<>();
        try (var connection = ConnectionManager.open();
             var statement = connection.createStatement()) {
            var resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                result.add(resultSet.getObject("id", Long.class)); // null safe
            }
        }
        return result;
    }

}


//String sql = """
//                INSERT INTO info (data)
//                VALUES
//                ('autogenerated')
//                """;
//        try (var connection = ConnectionManager.open();
//var statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
//        System.out.println(connection.getSchema());
//        System.out.println(connection.getTransactionIsolation());
//
//var executeResult = statement.executeUpdate(sql,Statement.RETURN_GENERATED_KEYS);
//var generatedKeys = statement.getGeneratedKeys();
//            if (generatedKeys.next()){
//var generatedId = generatedKeys.getInt("id");
//                System.out.println(generatedId);
//            }
////            while (executeResult.next()) {
////                System.out.println(executeResult.getLong("id"));
////                System.out.println(executeResult.getString("passenger_no"));
////                System.out.println(executeResult.getBigDecimal("cost"));
//////                executeResult.previous();
//////                executeResult.afterLast();
////                System.out.println("----------------");
////            }
//                    }